### ISSUE TITLE
Error: Unknown property "wantpartslist" for BggCollectionItemDto

### ISSUE THREAD

**Issue by Northburns** [LearningProcesss/boardgamegeekjsclient#32]
This is the same as #19 but for property "wantpartslist". No rush on my part, my project can circumnavigate around that 😊 Would it be possible and/or make sense to warn about unknown properties instead of erroring about them 🤷‍♂️

**Comment by LearningProcesss** [comment]
It certainly makes sense, while i'm searching a way and waiting the library's dev,
i will add each property when they come up.
