### ISSUE TITLE
 Collection query with `version` leads to Error: Unknown property "version" for BggCollectionItemDto

### ISSUE THREAD

**Issue by Northburns** [LearningProcesss/boardgamegeekjsclient#33]
```javascript
const bgg = BggClient.Create();
const colResult = await bgg.collection.query({
    username: config.bgg.username,
    version: 1, // <--
    own: 1,
});
```

results in `t [Error]: Unknown property "version" for BggCollectionItemDto at ...`. 

For context, I used my collection (same username as my GitHub username) and the offending collection item was `{"name":"6 nimmt!","yearpublished":2007, .... "objectid":432,", ....}`

Let me know if there's any more info I can provide 😊

**Comment by LearningProcesss** [comment]
Fixed with 1.6.0
Let me know
