### ISSUE TITLE
Exception thrown when accessing a game without versions

### ISSUE THREAD

**Issue by rgembalik** [LearningProcesss/boardgamegeekjsclient#36]
I stumbled upon this use case:
```
await client.thing.query({id: [21659], versions: 1})
```
```
Uncaught TypeError: Cannot read properties of undefined (reading 'item')
    at Object.using (node_modules\boardgamegeekclient\dist\cjs\dto\concrete\BggThingDto.js:148:36)
    at e.parseJsonDeserializeProperty (node_modules\jackson-js\dist\lib.node.js:16:92732)
    at e.deepTransform (node_modules\jackson-js\dist\lib.node.js:16:75148)
    at e.parseIterable (node_modules\jackson-js\dist\lib.node.js:16:99411)
    at e.deepTransform (node_modules\jackson-js\dist\lib.node.js:16:75380)
    at e.transform (node_modules\jackson-js\dist\lib.node.js:16:71069)
    at node_modules\boardgamegeekclient\dist\cjs\dto\dtoparser\concrete\BggThingDtoParser.js:12:33
    at new Promise (<anonymous>)
    at BggThingDtoParser.jsonToDto (node_modules\boardgamegeekclient\dist\cjs\dto\dtoparser\concrete\BggThingDtoParser.js:11:16)
```

It works ok when running without `versions`. My assumption is that it's because versions is a self-closed tag in this case. https://api.geekdo.com/xmlapi2/thing?id=21659&versions=1

Any idea how to work around it?

**Comment by LearningProcesss** [comment]
> I stumbled upon this use case:
> 
> ```
> await client.thing.query({id: [21659], versions: 1})
> ```
> 
> ```
> Uncaught TypeError: Cannot read properties of undefined (reading 'item')
>     at Object.using (node_modules\boardgamegeekclient\dist\cjs\dto\concrete\BggThingDto.js:148:36)
>     at e.parseJsonDeserializeProperty (node_modules\jackson-js\dist\lib.node.js:16:92732)
>     at e.deepTransform (node_modules\jackson-js\dist\lib.node.js:16:75148)
>     at e.parseIterable (node_modules\jackson-js\dist\lib.node.js:16:99411)
>     at e.deepTransform (node_modules\jackson-js\dist\lib.node.js:16:75380)
>     at e.transform (node_modules\jackson-js\dist\lib.node.js:16:71069)
>     at node_modules\boardgamegeekclient\dist\cjs\dto\dtoparser\concrete\BggThingDtoParser.js:12:33
>     at new Promise (<anonymous>)
>     at BggThingDtoParser.jsonToDto (node_modules\boardgamegeekclient\dist\cjs\dto\dtoparser\concrete\BggThingDtoParser.js:11:16)
> ```
> 
> It works ok when running without `versions`. My assumption is that it's because versions is a self-closed tag in this case. https://api.geekdo.com/xmlapi2/thing?id=21659&versions=1
> 
> Any idea how to work around it?

Hi @rgembalik,
thanks for pointing out this issue that is solved by 1.7.2 release.
