### ISSUE TITLE
Querying collections fails when trying to include stats

### ISSUE THREAD

**Issue by ericpoulinnz** [LearningProcesss/boardgamegeekjsclient#46]
I am trying to query a user's collection. It works fine when I just pass up a username, but as soon as I add "stats: 1" it just hangs (and I seem to get no errors in the console). It seems to be any username I try, but for one that definitely breaks, try `Vitho`

```
const params: ICollectionRequest = {
    username,
    stats: 1, // <- only works when this is removed
  };
  await bggClient.collection.query(params);
```

Thank you for this package, works really well generally.

**Comment by darekkay** [comment]
I have the same issue, but I get an error message:

> Unknown property "stats" for BggCollectionItemDto

Seems to be related to #19, #32 and #33

**Comment by darekkay** [comment]
Thank you very much for such a quick fix! It all works fine for me now 🙂
