### ISSUE TITLE
Querying plays fails silently for some users

### ISSUE THREAD

**Issue by ericpoulinnz** [LearningProcesss/boardgamegeekjsclient#49]
I have been getting mixed results retrieving plays from players.

This works
`await client.play.query({ username: 'mattiabanned' });`

However this one does not
`await client.play.query({ username: 'Vitho' });`

There is no response or any indication something is going wrong. Both users only have one play and the only difference I can see is that the player where it is failing has a comment in the play, so I wonder if this is the problem?

**Comment by ericpoulinnz** [comment]
Hey @LearningProcesss, I was just wondering how far off a fix for this might be?

**Comment by LearningProcesss** [comment]
> Hey @LearningProcesss, I was just wondering how far off a fix for this might be?

Ciao @ericpoulinnz i'm checking out this problem right now i'll do my best to resolve as soon as possible!

**Comment by ericpoulinnz** [comment]
Thank you!! 🙏

**Comment by ericpoulinnz** [comment]
Thank you for the quick turnaround!
