### ISSUE TITLE
No players are returned in when fetching plays

### ISSUE THREAD

**Issue by ericpoulinnz** [LearningProcesss/boardgamegeekjsclient#51]
I think this might be since the last release, but now there is no player information returned when fetching plays.

This can be tested even with the demo username on the readme `mattiabanned`

**Comment by ericpoulinnz** [comment]
@LearningProcesss just checking in on this one as I feel it is a pretty major issue and must be a regression? Also let me know if/how I can help. We are quite invested in getting this working and I have been a big fan of your library to date

**Comment by LearningProcesss** [comment]
Ciao @ericpoulinnz,
are you using 1.9.0?

**Comment by ericpoulinnz** [comment]
Yes I updated to get comments for play logs from your last fix (which works well ☺️)

**Comment by LearningProcesss** [comment]
I'm using fresh new environment and 1.9.0 plays works right.

Do you have any relevant piece of code that you can show to me?

**Comment by ericpoulinnz** [comment]
@LearningProcesss hmm, players are definitely not being retrieved for me using the latest.

in `package.json` :
```
"boardgamegeekclient": "^1.9.0",
```

Called here (comments show inputs):
```
export const getBggPlayPage = async (username: string, page: number) => {
  const params: IPlaysRequest = {
    username, // "mattiabanned"
    page, // 1
  };
  const raw = await bggClient.play.query(params);
  console.log(raw);
  console.log("stringify", JSON.stringify(raw));
};
```

Output:
```
LOG  [{"page": 1, "plays": [[BggPlaysPlayDto]], "total": 1, "userid": 1236367, "username": "mattiabanned"}]
LOG  stringify [{"userid":1236367,"total":1,"page":1,"username":"mattiabanned","plays":[{"item":{"subtypes":[{"value":"boardgame"},{"value":"boardgameimplementation"},{"value":"boardgameintegration"}],"name":"Mistfall","objecttype":"thing","objectid":168274},"comments":"this is the first comment line\nthis is the second comment line","players":{},"id":57445284,"date":"2017-12-03","quantity":1,"length":180,"incomplete":0,"nowinstats":0,"location":"Italy"}]}]
```

Response calling BGG's API directly has a player in the play log:
<img width="1143" alt="Screenshot 2023-08-19 at 09 27 12" src="https://github.com/LearningProcesss/boardgamegeekjsclient/assets/1167772/9ba988b5-3152-4584-b208-fd6d018a6adb">

**Comment by LearningProcesss** [comment]
Hej @ericpoulinnz thanks for pointing out this problem, 1.9.1 fix it.

**Comment by ericpoulinnz** [comment]
Thank you @LearningProcesss , working well!
